"""Add qr_code field to patient model

Revision ID: 131c1a0d754d
Revises: 4e320f2bc0d2
Create Date: 2025-02-26 20:05:23.256462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131c1a0d754d'
down_revision = '4e320f2bc0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('qr_code')

    # ### end Alembic commands ###
